// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs3NN0gjRbnI10-DDDihtwD1RPQtrogjA',
    appId: '1:217142638108:web:138ec673ea89bdd229d1d9',
    messagingSenderId: '217142638108',
    projectId: 'ingatku-bc503',
    authDomain: 'ingatku-bc503.firebaseapp.com',
    storageBucket: 'ingatku-bc503.firebasestorage.app',
    measurementId: 'G-S2C60F2DHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtQfd39JaFi4G3GT4vtyKr1FYqMsbuXCE',
    appId: '1:217142638108:android:f0997fa1a181e74b29d1d9',
    messagingSenderId: '217142638108',
    projectId: 'ingatku-bc503',
    storageBucket: 'ingatku-bc503.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIbNNaLvE_LASBAQ4YEMSXZUTVppZTGUc',
    appId: '1:217142638108:ios:2904edf357e0b63f29d1d9',
    messagingSenderId: '217142638108',
    projectId: 'ingatku-bc503',
    storageBucket: 'ingatku-bc503.firebasestorage.app',
    iosBundleId: 'com.example.ingatku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIbNNaLvE_LASBAQ4YEMSXZUTVppZTGUc',
    appId: '1:217142638108:ios:2904edf357e0b63f29d1d9',
    messagingSenderId: '217142638108',
    projectId: 'ingatku-bc503',
    storageBucket: 'ingatku-bc503.firebasestorage.app',
    iosBundleId: 'com.example.ingatku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs3NN0gjRbnI10-DDDihtwD1RPQtrogjA',
    appId: '1:217142638108:web:f68d0b8a8ada2cc229d1d9',
    messagingSenderId: '217142638108',
    projectId: 'ingatku-bc503',
    authDomain: 'ingatku-bc503.firebaseapp.com',
    storageBucket: 'ingatku-bc503.firebasestorage.app',
    measurementId: 'G-LDKMWG6X5G',
  );

}